using Microsoft.EntityFrameworkCore.Migrations.Operations;

namespace PC_ArchitectInstaller.Models
{
    public class CPU
    {
        public string Name { get; set; }//Name = the name of the processor
        public double Price { get; set; }//Price = the cost of the processor
        public int Core_count { get; set; }//Core Count = the number of cores in a processor
        public double Core_clock { get; set; }//Core Clock = the speed at which the processor operates
        public double Boost_clock { get; set; }//Boost Clock = the maximum frequency the processor can achieve under load
        public int Tdp { get; set; }//Thermal Design Power = maximum amount of heat generated by a computer chip or component
        public string Integraded_graphics { get; set; } = "";//Graphics = the integrated graphics of the processor
        public bool Smt { get; set; }//Simultaneous Multithreading = a technique for improving the performance of CPUs by allowing them to execute multiple threads simultaneously
    }
}